"""
DataFlowX Recursive Descent ANSI SQL Parser
Parses token streams generated by SQLTokenizer into strongly-typed AST nodes (SelectQueryAST, ColumnProjectionNode, BinaryOpNode).
"""

from typing import Any, List, Optional
from data_engine.sql_dialects.ast_nodes import (
    BinaryOpNode,
    ColumnProjectionNode,
    FunctionCallNode,
    IdentifierNode,
    JoinNode,
    LiteralNode,
    SelectQueryAST,
    TableRefNode,
)
from data_engine.sql_dialects.tokenizer import SQLTokenizer, Token, TokenType


class ANSIParser:
    """Recursive descent parser for SQL SELECT expressions."""

    def __init__(self, tokens: List[Token]):
        self.tokens = tokens
        self.cursor = 0

    def current_token(self) -> Token:
        if self.cursor < len(self.tokens):
            return self.tokens[self.cursor]
        return Token(type=TokenType.EOF, value="", position=-1)

    def advance(self) -> Token:
        tok = self.current_token()
        self.cursor += 1
        return tok

    def match_keyword(self, val: str) -> bool:
        tok = self.current_token()
        if tok.type == TokenType.KEYWORD and tok.value.upper() == val.upper():
            self.advance()
            return True
        return False

    def parse_select(self) -> SelectQueryAST:
        """Parse SELECT ... FROM ... WHERE ... GROUP BY ... ORDER BY ... LIMIT ..."""
        if not self.match_keyword("SELECT"):
            raise SyntaxError("Expected SELECT keyword at start of query")

        is_distinct = self.match_keyword("DISTINCT")
        projections = self.parse_projection_list()

        from_table = None
        if self.match_keyword("FROM"):
            from_table = self.parse_table_ref()

        joins = []
        while self.current_token().type == TokenType.KEYWORD and "JOIN" in self.current_token().value.upper():
            join_tok = self.advance().value.upper()
            tbl = self.parse_table_ref()
            cond = None
            if self.match_keyword("ON"):
                cond = self.parse_expression()
            joins.append(JoinNode(join_type=join_tok, table=tbl, condition=cond))

        where_clause = None
        if self.match_keyword("WHERE"):
            where_clause = self.parse_expression()

        group_by = []
        if self.match_keyword("GROUP"):
            self.match_keyword("BY")
            group_by = self.parse_identifier_list()

        order_by = []
        if self.match_keyword("ORDER"):
            self.match_keyword("BY")
            order_by = self.parse_order_by_list()

        limit = None
        if self.match_keyword("LIMIT"):
            lim_tok = self.advance()
            limit = int(lim_tok.value) if lim_tok.type == TokenType.NUMBER else None

        return SelectQueryAST(
            is_distinct=is_distinct,
            projections=projections,
            from_table=from_table,
            joins=joins,
            where_clause=where_clause,
            group_by=group_by,
            order_by=order_by,
            limit=limit
        )

    def parse_projection_list(self) -> List[ColumnProjectionNode]:
        projections = []
        while self.current_token().type != TokenType.EOF:
            if self.current_token().type == TokenType.KEYWORD and self.current_token().value.upper() in ("FROM", "WHERE"):
                break
            expr = self.parse_expression()
            alias = None
            if self.match_keyword("AS"):
                alias = self.advance().value
            elif self.current_token().type == TokenType.IDENTIFIER and self.current_token().value.upper() not in ("FROM", "WHERE"):
                alias = self.advance().value

            projections.append(ColumnProjectionNode(expression=expr, alias=alias))
            if self.current_token().value == ",":
                self.advance()
            else:
                break
        return projections

    def parse_table_ref(self) -> TableRefNode:
        tok = self.advance()
        parts = tok.value.split(".", 1)
        schema = parts[0] if len(parts) > 1 else None
        name = parts[1] if len(parts) > 1 else parts[0]

        alias = None
        if self.match_keyword("AS"):
            alias = self.advance().value
        elif self.current_token().type == TokenType.IDENTIFIER and self.current_token().value.upper() not in ("WHERE", "JOIN", "ON", "GROUP", "ORDER", "LIMIT"):
            alias = self.advance().value

        return TableRefNode(schema_name=schema, table_name=name, alias=alias)

    def parse_expression(self) -> Any:
        tok = self.advance()
        if tok.type == TokenType.IDENTIFIER:
            # Check for function call
            if self.current_token().value == "(":
                self.advance()
                args = []
                while self.current_token().value != ")":
                    args.append(self.parse_expression())
                    if self.current_token().value == ",":
                        self.advance()
                self.match_keyword(")")
                return FunctionCallNode(name=tok.value.upper(), arguments=args)
            return IdentifierNode(name=tok.value)
        elif tok.type == TokenType.NUMBER:
            return LiteralNode(value=float(tok.value) if "." in tok.value else int(tok.value), data_type="NUMBER")
        elif tok.type == TokenType.STRING:
            return LiteralNode(value=tok.value, data_type="STRING")
        return LiteralNode(value=tok.value, data_type="UNKNOWN")

    def parse_identifier_list(self) -> List[IdentifierNode]:
        ids = []
        while self.current_token().type == TokenType.IDENTIFIER:
            ids.append(IdentifierNode(name=self.advance().value))
            if self.current_token().value == ",":
                self.advance()
            else:
                break
        return ids

    def parse_order_by_list(self) -> List[Tuple[IdentifierNode, str]]:
        orders = []
        while self.current_token().type == TokenType.IDENTIFIER:
            col_id = IdentifierNode(name=self.advance().value)
            direction = "ASC"
            if self.match_keyword("DESC"):
                direction = "DESC"
            elif self.match_keyword("ASC"):
                direction = "ASC"
            orders.append((col_id, direction))
            if self.current_token().value == ",":
                self.advance()
            else:
                break
        return orders
