apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dataflowx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "dataflowx_user"
            - name: POSTGRES_PASSWORD
              value: "DataFlowXSecretPass2026!"
            - name: POSTGRES_DB
              value: "dataflowx_db"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dataflowx
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
