"""
DataFlowX Recursive Descent SQL Parser
Constructs typed AST nodes from token streams generated by the SQL lexer.
"""

from typing import Any, List, Optional
from data_engine.sql_parser.ast_nodes import (
    BinaryExpression, BinaryOp, CaseExpression, ColumnRef, FunctionCall,
    JoinClause, JoinType, Literal, OrderByItem, SelectItem, SelectStatement,
    SqlDataType, TableSource, UnaryExpression, UnaryOp, WhenClause
)
from data_engine.sql_parser.lexer import SQLLexer, Token, TokenType


class SQLParser:
    """Recursive descent parser for SQL queries."""

    def __init__(self, tokens: List[Token]):
        self.tokens = tokens
        self.pos = 0

    @classmethod
    def parse_sql(cls, sql: str) -> SelectStatement:
        lexer = SQLLexer(sql)
        tokens = lexer.tokenize()
        parser = cls(tokens)
        return parser.parse_select_statement()

    def _peek(self) -> Token:
        return self.tokens[self.pos]

    def _match(self, *expected_values: str) -> bool:
        tok = self._peek()
        if tok.token_type in (TokenType.KEYWORD, TokenType.OPERATOR, TokenType.PUNCTUATION):
            return tok.value.upper() in [v.upper() for v in expected_values]
        return False

    def _consume(self, *expected_values: str) -> Token:
        tok = self._peek()
        if expected_values:
            if not self._match(*expected_values):
                raise SyntaxError(f"Expected {expected_values} at line {tok.line}, col {tok.column}, found '{tok.value}'")
        self.pos += 1
        return tok

    def parse_select_statement(self) -> SelectStatement:
        self._consume("SELECT")
        is_distinct = False
        if self._match("DISTINCT"):
            self._consume("DISTINCT")
            is_distinct = True

        projections = self._parse_projection_list()
        from_table = None
        joins: List[JoinClause] = []

        if self._match("FROM"):
            self._consume("FROM")
            from_table = self._parse_table_source()

            while self._match("JOIN", "INNER", "LEFT", "RIGHT", "FULL", "CROSS"):
                joins.append(self._parse_join_clause())

        where_clause = None
        if self._match("WHERE"):
            self._consume("WHERE")
            where_clause = self._parse_expression()

        group_by = []
        if self._match("GROUP"):
            self._consume("GROUP")
            self._consume("BY")
            group_by = self._parse_expression_list()

        having_clause = None
        if self._match("HAVING"):
            self._consume("HAVING")
            having_clause = self._parse_expression()

        order_by = []
        if self._match("ORDER"):
            self._consume("ORDER")
            self._consume("BY")
            order_by = self._parse_order_by_list()

        limit = None
        if self._match("LIMIT"):
            self._consume("LIMIT")
            limit_tok = self._consume()
            limit = int(limit_tok.value)

        return SelectStatement(
            is_distinct=is_distinct,
            projection=projections,
            from_table=from_table,
            joins=joins,
            where_clause=where_clause,
            group_by=group_by,
            having_clause=having_clause,
            order_by=order_by,
            limit=limit
        )

    def _parse_projection_list(self) -> List[SelectItem]:
        items = []
        while True:
            expr = self._parse_expression()
            alias = None
            if self._match("AS"):
                self._consume("AS")
                alias_tok = self._consume()
                alias = alias_tok.value
            elif self._peek().token_type == TokenType.IDENTIFIER and not self._match("FROM", "WHERE", "JOIN"):
                alias_tok = self._consume()
                alias = alias_tok.value

            items.append(SelectItem(expression=expr, alias=alias))
            if self._match(","):
                self._consume(",")
            else:
                break
        return items

    def _parse_table_source(self) -> TableSource:
        table_tok = self._consume()
        schema_name = None
        table_name = table_tok.value

        if self._match("."):
            self._consume(".")
            second_tok = self._consume()
            schema_name = table_name
            table_name = second_tok.value

        alias = None
        if self._match("AS"):
            self._consume("AS")
            alias = self._consume().value
        elif self._peek().token_type == TokenType.IDENTIFIER and not self._match("WHERE", "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "CROSS", "GROUP", "ORDER", "LIMIT"):
            alias = self._consume().value

        return TableSource(table_name=table_name, schema_name=schema_name, alias=alias)

    def _parse_join_clause(self) -> JoinClause:
        join_type = JoinType.INNER
        if self._match("LEFT"):
            self._consume("LEFT")
            if self._match("JOIN"):
                self._consume("JOIN")
            join_type = JoinType.LEFT
        elif self._match("RIGHT"):
            self._consume("RIGHT")
            if self._match("JOIN"):
                self._consume("JOIN")
            join_type = JoinType.RIGHT
        elif self._match("FULL"):
            self._consume("FULL")
            if self._match("OUTER"):
                self._consume("OUTER")
            if self._match("JOIN"):
                self._consume("JOIN")
            join_type = JoinType.FULL
        elif self._match("INNER"):
            self._consume("INNER")
            self._consume("JOIN")
            join_type = JoinType.INNER
        elif self._match("CROSS"):
            self._consume("CROSS")
            self._consume("JOIN")
            join_type = JoinType.CROSS
        elif self._match("JOIN"):
            self._consume("JOIN")
            join_type = JoinType.INNER

        right_table = self._parse_table_source()
        on_cond = None
        if self._match("ON"):
            self._consume("ON")
            on_cond = self._parse_expression()

        return JoinClause(join_type=join_type, right_table=right_table, on_condition=on_cond)

    def _parse_expression(self) -> Any:
        return self._parse_or()

    def _parse_or(self) -> Any:
        expr = self._parse_and()
        while self._match("OR"):
            self._consume("OR")
            right = self._parse_and()
            expr = BinaryExpression(left=expr, op=BinaryOp.OR, right=right)
        return expr

    def _parse_and(self) -> Any:
        expr = self._parse_comparison()
        while self._match("AND"):
            self._consume("AND")
            right = self._parse_comparison()
            expr = BinaryExpression(left=expr, op=BinaryOp.AND, right=right)
        return expr

    def _parse_comparison(self) -> Any:
        expr = self._parse_addition()
        if self._match("=", "!=", "<>", ">", ">=", "<", "<=", "LIKE", "ILIKE"):
            op_tok = self._consume()
            op_str = op_tok.value
            op = BinaryOp.EQ if op_str == "=" else BinaryOp.NEQ if op_str in ("!=", "<>") else BinaryOp(op_str)
            right = self._parse_addition()
            return BinaryExpression(left=expr, op=op, right=right)
        return expr

    def _parse_addition(self) -> Any:
        expr = self._parse_multiplication()
        while self._match("+", "-"):
            op_tok = self._consume()
            op = BinaryOp.ADD if op_tok.value == "+" else BinaryOp.SUB
            right = self._parse_multiplication()
            expr = BinaryExpression(left=expr, op=op, right=right)
        return expr

    def _parse_multiplication(self) -> Any:
        expr = self._parse_primary()
        while self._match("*", "/", "%"):
            op_tok = self._consume()
            op = BinaryOp.MUL if op_tok.value == "*" else BinaryOp.DIV if op_tok.value == "/" else BinaryOp.MOD
            right = self._parse_primary()
            expr = BinaryExpression(left=expr, op=op, right=right)
        return expr

    def _parse_primary(self) -> Any:
        tok = self._peek()

        if tok.token_type == TokenType.NUMERIC_LITERAL:
            self._consume()
            val = float(tok.value) if "." in tok.value else int(tok.value)
            return Literal(value=val, data_type=SqlDataType.FLOAT if "." in tok.value else SqlDataType.BIGINT)

        if tok.token_type == TokenType.STRING_LITERAL:
            self._consume()
            return Literal(value=tok.value, data_type=SqlDataType.STRING)

        if self._match("("):
            self._consume("(")
            expr = self._parse_expression()
            self._consume(")")
            return expr

        if tok.token_type == TokenType.IDENTIFIER or tok.token_type == TokenType.KEYWORD:
            # Check function call
            if self.pos + 1 < len(self.tokens) and self.tokens[self.pos + 1].value == "(":
                fn_name = self._consume().value
                self._consume("(")
                args = []
                if not self._match(")"):
                    args = self._parse_expression_list()
                self._consume(")")
                return FunctionCall(function_name=fn_name, arguments=args)

            col_tok = self._consume()
            col_name = col_tok.value
            table_name = None
            if self._match("."):
                self._consume(".")
                second = self._consume()
                table_name = col_name
                col_name = second.value
            return ColumnRef(column_name=col_name, table_name=table_name)

        self._consume()
        return ColumnRef(column_name=tok.value)

    def _parse_expression_list(self) -> List[Any]:
        items = []
        while True:
            items.append(self._parse_expression())
            if self._match(","):
                self._consume(",")
            else:
                break
        return items

    def _parse_order_by_list(self) -> List[OrderByItem]:
        items = []
        while True:
            expr = self._parse_expression()
            asc = True
            if self._match("DESC"):
                self._consume("DESC")
                asc = False
            elif self._match("ASC"):
                self._consume("ASC")
                asc = True
            items.append(OrderByItem(expression=expr, ascending=asc))
            if self._match(","):
                self._consume(",")
            else:
                break
        return items
